CREATE SCHEMA IF NOT EXISTS marts;

CREATE TABLE IF NOT EXISTS marts.era5_hourly (
  region TEXT NOT NULL,
  ts TIMESTAMP NOT NULL,
  t2m DOUBLE PRECISION,
  d2m DOUBLE PRECISION,
  tp DOUBLE PRECISION,
  u10 DOUBLE PRECISION,
  v10 DOUBLE PRECISION,
  swvl1 DOUBLE PRECISION,
  swvl2 DOUBLE PRECISION,
  wind_speed_10m DOUBLE PRECISION,
  PRIMARY KEY (region, ts)
);

CREATE TABLE IF NOT EXISTS marts.era5_daily (
  region TEXT NOT NULL,
  day DATE NOT NULL,
  t2m_mean DOUBLE PRECISION,
  t2m_min DOUBLE PRECISION,
  t2m_max DOUBLE PRECISION,
  d2m_mean DOUBLE PRECISION,
  tp_sum DOUBLE PRECISION,
  swvl1_mean DOUBLE PRECISION,
  swvl2_mean DOUBLE PRECISION,
  wind_speed_10m_mean DOUBLE PRECISION,
  PRIMARY KEY (region, day)
);
